vim.opt.autoindent = true
vim.opt.colorcolumn = "80"
vim.opt.cursorline = true
vim.opt.expandtab = true
vim.opt.hlsearch = false
vim.opt.ignorecase = true --ignore case during searches
vim.opt.incsearch = true --incremental search
vim.opt.lazyredraw = true
vim.opt.nu = true --line numbers
vim.opt.relativenumber = true --relative line numbers
vim.opt.scrolloff = 12
vim.opt.shiftwidth = 2
vim.opt.signcolumn = "yes"
vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.softtabstop = 2
vim.opt.tabstop = 2
vim.opt.termguicolors = true
vim.opt.undofile = true --persistant undo file history
vim.opt.updatetime = 50 --speed up plugin wait time
vim.opt.wrap = false --no line wrapping
